import { ThemeType } from "./themeMapping";

export const themeVariables: Record<ThemeType, Record<string, string>> = {
  ATELIER: {
    "--color-on-surface": "#1b1c18",
    "--color-surface": "#fbf9f2",
    "--color-surface-container-low": "#f5f4ed",
    "--color-surface-container": "#f0eee7",
    "--color-surface-container-high": "#eae8e1",
    "--color-surface-container-highest": "#e8e5d9",
    "--color-primary": "#735c00",
    "--color-primary-container": "#d4af37",
    "--color-secondary": "#6a5b56",
    "--color-outline": "#7f7663",
    "--color-outline-variant": "#d0c5af",
    "--color-error": "#ba1a1a",
    "--font-headline": "'Noto Serif', serif",
    "--font-body": "'Manrope', sans-serif",
    "--font-label": "'Manrope', sans-serif",
    "--radius-base": "0.125rem",
  },
  /** Stitch "Memento Summit" design system — Digital Memory Booklet project */
  CONFERENCE: {
    "--color-surface": "#0b1326",
    "--color-surface-dim": "#0b1326",
    "--color-surface-bright": "#31394d",
    "--color-surface-container-lowest": "#060e20",
    "--color-surface-container-low": "#131b2e",
    "--color-surface-container": "#171f33",
    "--color-surface-container-high": "#222a3d",
    "--color-surface-container-highest": "#2d3449",
    "--color-on-surface": "#dae2fd",
    "--color-on-surface-variant": "#c4c5d9",
    "--color-primary": "#b8c3ff",
    "--color-primary-container": "#2e5bff",
    "--color-on-primary": "#002388",
    "--color-on-primary-container": "#efefff",
    "--color-secondary": "#bec6e0",
    "--color-secondary-container": "#3f465c",
    "--color-on-secondary-container": "#adb4ce",
    "--color-tertiary": "#4edea3",
    "--color-tertiary-container": "#007d55",
    "--color-on-tertiary-container": "#bdffdb",
    "--color-outline": "#8e90a2",
    "--color-outline-variant": "#434656",
    "--color-error": "#ffb4ab",
    "--font-headline": "'Inter', sans-serif",
    "--font-body": "'Manrope', sans-serif",
    "--font-label": "'Inter', sans-serif",
    "--radius-base": "0.125rem",
  },
  JUBILEE: {
    "--color-on-surface": "#ffffff",
    "--color-surface": "#210219",
    "--color-surface-container-low": "#330325",
    "--color-surface-container": "#3a042a",
    "--color-surface-container-high": "#450532",
    "--color-surface-container-highest": "rgba(255, 46, 151, 0.1)",
    "--color-primary": "#ff2e97",
    "--color-primary-container": "#ba005d",
    "--color-secondary": "#ff88b5",
    "--color-outline": "rgba(255, 46, 151, 0.6)",
    "--color-outline-variant": "rgba(255, 46, 151, 0.2)",
    "--color-error": "#ff2e97",
    "--font-headline": "'Plus Jakarta Sans', sans-serif",
    "--font-body": "'Plus Jakarta Sans', sans-serif",
    "--font-label": "'Plus Jakarta Sans', sans-serif",
    "--radius-base": "9999px",
  },
  REVEAL: {
    "--color-on-surface": "#1a1c1c",
    "--color-surface": "#f9f9f9",
    "--color-surface-container-low": "#ffffff",
    "--color-surface-container": "#f3f3f3",
    "--color-surface-container-high": "#f0f0f0",
    "--color-surface-container-highest": "#e8e8e8",
    "--color-primary": "#4b626a",
    "--color-primary-container": "#aec6cf",
    "--color-secondary": "#42484a",
    "--color-outline": "#b2cad3",
    "--color-outline-variant": "rgba(194, 199, 202, 0.5)",
    "--color-error": "#ba1a1a",
    "--font-headline": "'Noto Serif', serif",
    "--font-body": "'Plus Jakarta Sans', sans-serif",
    "--font-label": "'Plus Jakarta Sans', sans-serif",
    "--radius-base": "0.75rem",
  }
};
